use std::collections::HashMap;
use std::iter::FromIterator;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Naturality {
    Natural,
    Pond,
    Exploited,
    Planted,
    Built,
    Unknown,
}

pub fn get_naturality_color(n: &Naturality) -> u32 {
    match n {
        Naturality::Natural     => 0xff448844, // dark green muted
        Naturality::Pond        => 0xff886644, // dark blue-green muted
        Naturality::Exploited   => 0xffaaaaaa, // bright gray
        Naturality::Planted     => 0xff88ffff, // bright yellow
        Naturality::Built       => 0xff88bbff, // bright orange
        Naturality::Unknown     => 0x88ff00ff, // fuchsia semi-transparent
    }
}

// CCNATURAL_COLORS_BLOCKS_BIOME must be checked before CCNATURAL_COLORS_BLOCK_DEFAULT
// the split is just to make this file shorter

lazy_static! {
    pub static ref CCNATURAL_COLORS_BLOCK_DEFAULT: HashMap<&'static str, Naturality> = HashMap::from_iter([
("acacia_door", Naturality::Built),
("acacia_fence", Naturality::Built),
("acacia_fence_gate", Naturality::Built),
("acacia_stairs", Naturality::Built),
("activator_rail", Naturality::Built),
("anvil", Naturality::Built),
("beacon", Naturality::Built),
("bed", Naturality::Built),
("bedrock", Naturality::Exploited),
("beetroots", Naturality::Planted),
("birch_door", Naturality::Built),
("birch_fence", Naturality::Built),
("birch_fence_gate", Naturality::Built),
("birch_stairs", Naturality::Built),
("black_glazed_terracotta", Naturality::Built),
("blue_glazed_terracotta", Naturality::Built),
("bone_block", Naturality::Built),
("bookshelf", Naturality::Built),
("brewing_stand", Naturality::Built),
("brick_block", Naturality::Built),
("brick_stairs", Naturality::Built),
("brown_glazed_terracotta", Naturality::Built),
("brown_mushroom", Naturality::Unknown),
("brown_mushroom_block", Naturality::Built),
("cactus", Naturality::Planted),
("cake", Naturality::Built),
("carpet", Naturality::Built),
("carrots", Naturality::Planted),
("cauldron", Naturality::Built),
("chest", Naturality::Built),
("chorus_flower", Naturality::Planted),
("chorus_plant", Naturality::Planted),
("clay", Naturality::Unknown),
("coal_block", Naturality::Built),
("coal_ore", Naturality::Exploited),
("cobblestone", Naturality::Built),
("cobblestone_wall", Naturality::Built),
("cocoa", Naturality::Planted),
("concrete", Naturality::Built),
("concrete_powder", Naturality::Built),
("crafting_table", Naturality::Built),
("dark_oak_door", Naturality::Built),
("dark_oak_fence", Naturality::Built),
("dark_oak_fence_gate", Naturality::Built),
("dark_oak_stairs", Naturality::Built),
("daylight_detector", Naturality::Built),
("daylight_detector_inverted", Naturality::Built),
("deadbush", Naturality::Unknown),
("detector_rail", Naturality::Built),
("diamond_block", Naturality::Built),
("diamond_ore", Naturality::Exploited),
("dirt", Naturality::Exploited),
("dispenser", Naturality::Built),
("double_plant", Naturality::Unknown),
("double_stone_slab", Naturality::Built),
("double_stone_slab2", Naturality::Built),
("double_wooden_slab", Naturality::Built),
("dropper", Naturality::Built),
("emerald_block", Naturality::Built),
("enchanting_table", Naturality::Built),
("end_bricks", Naturality::Built),
("end_rod", Naturality::Built),
("end_stone", Naturality::Built),
("farmland", Naturality::Planted),
("fence", Naturality::Built),
("fence_gate", Naturality::Built),
("fire", Naturality::Unknown),
("flower_pot", Naturality::Built),
("flowing_lava", Naturality::Unknown),
("flowing_water", Naturality::Unknown),
("furnace", Naturality::Built),
("glass", Naturality::Built),
("glass_pane", Naturality::Built),
("glowstone", Naturality::Built),
("gold_block", Naturality::Built),
("gold_ore", Naturality::Exploited),
("golden_rail", Naturality::Built),
("grass", Naturality::Natural),
("grass_path", Naturality::Built),
("gravel", Naturality::Exploited),
("gray_glazed_terracotta", Naturality::Built),
("green_glazed_terracotta", Naturality::Built),
("hardened_clay", Naturality::Built),
("hay_block", Naturality::Built),
("heavy_weighted_pressure_plate", Naturality::Built),
("hopper", Naturality::Built),
("ice", Naturality::Built),
("iron_bars", Naturality::Built),
("iron_block", Naturality::Built),
("iron_door", Naturality::Built),
("iron_ore", Naturality::Exploited),
("iron_trapdoor", Naturality::Built),
("jukebox", Naturality::Built),
("jungle_door", Naturality::Built),
("jungle_fence", Naturality::Built),
("jungle_fence_gate", Naturality::Built),
("jungle_stairs", Naturality::Built),
("ladder", Naturality::Built),
("lapis_block", Naturality::Built),
("lapis_ore", Naturality::Exploited),
("lava", Naturality::Unknown),
("leaves", Naturality::Natural),
("leaves2", Naturality::Planted),
("lever", Naturality::Built),
("light_blue_glazed_terracotta", Naturality::Built),
("light_weighted_pressure_plate", Naturality::Built),
("lime_glazed_terracotta", Naturality::Built),
("lit_pumpkin", Naturality::Built),
("lit_redstone_lamp", Naturality::Built),
("lit_redstone_ore", Naturality::Exploited),
("log", Naturality::Unknown),
("log2", Naturality::Unknown),
("magma", Naturality::Built),
("melon_block", Naturality::Unknown),
("melon_stem", Naturality::Unknown),
("mob_spawner", Naturality::Unknown),
("mossy_cobblestone", Naturality::Exploited),
("mycelium", Naturality::Built),
("nether_brick", Naturality::Built),
("nether_brick_fence", Naturality::Built),
("nether_brick_stairs", Naturality::Built),
("nether_wart", Naturality::Planted),
("nether_wart_block", Naturality::Built),
("netherrack", Naturality::Built),
("noteblock", Naturality::Built),
("oak_stairs", Naturality::Built),
("observer", Naturality::Built),
("obsidian", Naturality::Built),
("orange_glazed_terracotta", Naturality::Built),
("packed_ice", Naturality::Built),
("pink_glazed_terracotta", Naturality::Built),
("piston", Naturality::Built),
("piston_head", Naturality::Built),
("planks", Naturality::Built),
("potatoes", Naturality::Planted),
("powered_repeater", Naturality::Built),
("prismarine", Naturality::Unknown),
("pumpkin", Naturality::Planted),
("pumpkin_stem", Naturality::Planted),
("purple_glazed_terracotta", Naturality::Built),
("purpur_block", Naturality::Built),
("purpur_double_slab", Naturality::Built),
("purpur_pillar", Naturality::Built),
("purpur_slab", Naturality::Built),
("purpur_stairs", Naturality::Built),
("quartz_block", Naturality::Built),
("quartz_ore", Naturality::Built),
("quartz_stairs", Naturality::Built),
("rail", Naturality::Built),
("red_flower", Naturality::Unknown),
("red_glazed_terracotta", Naturality::Built),
("red_mushroom", Naturality::Built),
("red_mushroom_block", Naturality::Built),
("red_nether_brick", Naturality::Built),
("red_sandstone", Naturality::Built),
("red_sandstone_stairs", Naturality::Built),
("redstone_block", Naturality::Built),
("redstone_lamp", Naturality::Built),
("redstone_ore", Naturality::Exploited),
("redstone_torch", Naturality::Built),
("redstone_wire", Naturality::Built),
("reeds", Naturality::Unknown),
("sand", Naturality::Unknown),
("sandstone", Naturality::Built),
("sandstone_stairs", Naturality::Built),
("sapling", Naturality::Built),
("sea_lantern", Naturality::Built),
("silver_glazed_terracotta", Naturality::Built),
("skull", Naturality::Built),
("slime", Naturality::Built),
("snow", Naturality::Built),
("snow_layer", Naturality::Built),
("soul_sand", Naturality::Built),
("spruce_door", Naturality::Built),
("spruce_fence", Naturality::Built),
("spruce_fence_gate", Naturality::Built),
("spruce_stairs", Naturality::Built),
("stained_glass", Naturality::Built),
("stained_glass_pane", Naturality::Built),
("stained_hardened_clay", Naturality::Built),
("standing_banner", Naturality::Built),
("standing_sign", Naturality::Built),
("sticky_piston", Naturality::Built),
("stone", Naturality::Exploited),
("stone_brick_stairs", Naturality::Built),
("stone_button", Naturality::Built),
("stone_pressure_plate", Naturality::Built),
("stone_slab", Naturality::Built),
("stone_slab2", Naturality::Built),
("stone_stairs", Naturality::Built),
("stonebrick", Naturality::Built),
("tallgrass", Naturality::Unknown),
("tnt", Naturality::Built),
("torch", Naturality::Built),
("trapdoor", Naturality::Built),
("trapped_chest", Naturality::Built),
("tripwire", Naturality::Built),
("tripwire_hook", Naturality::Built),
("unlit_redstone_torch", Naturality::Built),
("unpowered_comparator", Naturality::Built),
("unpowered_repeater", Naturality::Built),
("vine", Naturality::Unknown),
("wall_banner", Naturality::Built),
("wall_sign", Naturality::Built),
("water", Naturality::Pond),
("waterlily", Naturality::Built),
("web", Naturality::Built),
("wheat", Naturality::Planted),
("white_glazed_terracotta", Naturality::Built),
("wooden_button", Naturality::Built),
("wooden_door", Naturality::Built),
("wooden_pressure_plate", Naturality::Built),
("wooden_slab", Naturality::Built),
("wool", Naturality::Built),
("yellow_flower", Naturality::Built),
("yellow_glazed_terracotta", Naturality::Built),
    ].iter().map(|(n,c)| (*n, *c)));

    pub static ref CCNATURAL_COLORS_BLOCK_BIOME: HashMap<(&'static str, u8), Naturality> = HashMap::from_iter([
(("brown_mushroom", 4), Naturality::Natural),
(("brown_mushroom", 6), Naturality::Natural),
(("brown_mushroom", 14), Naturality::Natural),
(("brown_mushroom_block", 14), Naturality::Natural),
(("brown_mushroom_block", 29), Naturality::Natural),
(("brown_mushroom_block", 157), Naturality::Natural),
(("cactus", 2), Naturality::Natural),
(("cactus", 130), Naturality::Natural),
(("clay", 0), Naturality::Natural),
(("clay", 7), Naturality::Natural),
(("clay", 6), Naturality::Natural),
(("clay", 4), Naturality::Exploited),
(("clay", 13), Naturality::Exploited),
(("clay", 14), Naturality::Exploited),
(("clay", 21), Naturality::Exploited),
(("clay", 133), Naturality::Exploited),
(("clay", 158), Naturality::Exploited),
(("clay", 11), Naturality::Exploited),
(("clay", 17), Naturality::Exploited),
(("clay", 36), Naturality::Exploited),
(("clay", 12), Naturality::Exploited),
(("clay", 27), Naturality::Exploited),
(("clay", 31), Naturality::Exploited),
(("clay", 28), Naturality::Exploited),
(("cocoa", 21), Naturality::Natural),
(("cocoa", 149), Naturality::Natural),
(("deadbush", 2), Naturality::Natural),
(("deadbush", 167), Naturality::Natural),
(("deadbush", 39), Naturality::Natural),
(("deadbush", 166), Naturality::Natural),
(("deadbush", 38), Naturality::Natural),
(("deadbush", 130), Naturality::Natural),
(("deadbush", 7), Naturality::Built),
(("deadbush", 1), Naturality::Built),
(("deadbush", 29), Naturality::Built),
(("deadbush", 12), Naturality::Built),
(("deadbush", 24), Naturality::Built),
(("dirt", 0), Naturality::Natural),
(("dirt", 7), Naturality::Natural),
(("dirt", 166), Naturality::Natural),
(("dirt", 38), Naturality::Natural),
(("dirt", 3), Naturality::Natural),
(("dirt", 6), Naturality::Natural),
(("dirt", 163), Naturality::Natural),
(("dirt", 11), Naturality::Natural),
(("dirt", 24), Naturality::Natural),
(("dirt", 8), Naturality::Built),
(("dirt", 27), Naturality::Unknown),
(("dirt", 12), Naturality::Unknown),
(("dirt", 17), Naturality::Unknown),
(("dirt", 30), Naturality::Unknown),
(("dirt", 19), Naturality::Unknown),
(("dirt", 28), Naturality::Unknown),
(("dirt", 36), Naturality::Unknown),
(("dirt", 25), Naturality::Unknown),
(("dirt", 37), Naturality::Unknown),
(("dirt", 32), Naturality::Unknown),
(("dirt", 26), Naturality::Unknown),
(("dirt", 156), Naturality::Unknown),
(("dirt", 131), Naturality::Unknown),
(("dirt", 155), Naturality::Unknown),
(("dirt", 134), Naturality::Unknown),
(("dirt", 165), Naturality::Unknown),
(("dirt", 15), Naturality::Unknown),
(("dirt", 164), Naturality::Unknown),
(("dirt", 31), Naturality::Unknown),
(("dirt", 162), Naturality::Unknown),
(("dirt", 33), Naturality::Unknown),
(("flowing_lava", 8), Naturality::Natural),
(("glowstone", 8), Naturality::Natural),
(("grass", 7), Naturality::Unknown),
(("grass", 140), Naturality::Unknown),
(("grass", 12), Naturality::Unknown),
(("grass", 36), Naturality::Unknown),
(("grass", 28), Naturality::Unknown),
(("grass", 11), Naturality::Unknown),
(("grass", 25), Naturality::Unknown),
(("grass", 30), Naturality::Unknown),
(("grass", 32), Naturality::Unknown),
(("grass", 19), Naturality::Unknown),
(("grass", 33), Naturality::Unknown),
(("grass", 37), Naturality::Unknown),
(("grass", 26), Naturality::Unknown),
(("grass", 162), Naturality::Unknown),
(("grass", 131), Naturality::Unknown),
(("grass", 15), Naturality::Unknown),
(("grass", 134), Naturality::Unknown),
(("grass", 0), Naturality::Built),
(("grass", 2), Naturality::Built),
(("grass", 130), Naturality::Built),
(("grass", 14), Naturality::Built),
(("grass", 8), Naturality::Built),
(("grass", 24), Naturality::Built),
(("grass", 39), Naturality::Planted),
(("gravel", 24), Naturality::Natural),
(("hardened_clay", 167), Naturality::Natural),
(("hardened_clay", 39), Naturality::Natural),
(("hardened_clay", 166), Naturality::Natural),
(("hardened_clay", 38), Naturality::Natural),
(("ice", 13), Naturality::Natural),
(("ice", 11), Naturality::Natural),
(("ice", 140), Naturality::Natural),
(("ice", 158), Naturality::Natural),
(("ice", 133), Naturality::Natural),
(("ice", 3), Naturality::Unknown),
(("ice", 20), Naturality::Unknown),
(("ice", 34), Naturality::Unknown),
(("lava", 8), Naturality::Natural),
(("leaves", 13), Naturality::Planted),
(("leaves", 163), Naturality::Planted),
(("leaves", 2), Naturality::Planted),
(("leaves", 14), Naturality::Planted),
(("leaves", 39), Naturality::Planted),
(("leaves", 0), Naturality::Built),
(("leaves", 8), Naturality::Built),
(("leaves", 24), Naturality::Built),
(("leaves", 130), Naturality::Unknown),
(("leaves", 19), Naturality::Unknown),
(("leaves", 36), Naturality::Unknown),
(("leaves", 30), Naturality::Unknown),
(("leaves", 37), Naturality::Unknown),
(("leaves", 162), Naturality::Unknown),
(("leaves", 33), Naturality::Unknown),
(("leaves", 134), Naturality::Unknown),
(("leaves", 23), Naturality::Unknown),
(("leaves", 15), Naturality::Unknown),
(("leaves", 26), Naturality::Unknown),
(("leaves", 131), Naturality::Unknown),
(("leaves2", 29), Naturality::Natural),
(("leaves2", 35), Naturality::Natural),
(("leaves2", 157), Naturality::Natural),
(("leaves2", 163), Naturality::Natural),
(("leaves2", 7), Naturality::Natural),
(("leaves2", 12), Naturality::Natural),
(("leaves2", 36), Naturality::Natural),
(("leaves2", 27), Naturality::Natural),
(("leaves2", 17), Naturality::Natural),
(("leaves2", 132), Naturality::Unknown),
(("leaves2", 22), Naturality::Unknown),
(("leaves2", 130), Naturality::Unknown),
(("leaves2", 20), Naturality::Unknown),
(("leaves2", 3), Naturality::Unknown),
(("leaves2", 13), Naturality::Unknown),
(("leaves2", 30), Naturality::Unknown),
(("leaves2", 5), Naturality::Unknown),
(("leaves2", 134), Naturality::Unknown),
(("leaves2", 26), Naturality::Unknown),
(("leaves2", 37), Naturality::Unknown),
(("leaves2", 8), Naturality::Built),
(("leaves2", 0), Naturality::Built),
(("leaves2", 24), Naturality::Built),
(("log", 4), Naturality::Exploited),
(("log", 1), Naturality::Exploited),
(("log", 3), Naturality::Exploited),
(("log", 6), Naturality::Exploited),
(("log", 18), Naturality::Exploited),
(("log", 5), Naturality::Exploited),
(("log", 21), Naturality::Exploited),
(("log", 129), Naturality::Exploited),
(("log", 132), Naturality::Exploited),
(("log", 149), Naturality::Exploited),
(("log", 157), Naturality::Exploited),
(("log", 22), Naturality::Exploited),
(("log", 35), Naturality::Planted),
(("log", 0), Naturality::Built),
(("log", 8), Naturality::Built),
(("log2", 29), Naturality::Exploited),
(("log2", 129), Naturality::Exploited),
(("log2", 163), Naturality::Exploited),
(("log2", 157), Naturality::Exploited),
(("log2", 35), Naturality::Natural),
(("log2", 8), Naturality::Built),
(("magma", 8), Naturality::Natural),
(("mossy_cobblestone", 21), Naturality::Unknown),
(("mossy_cobblestone", 149), Naturality::Unknown),
(("mossy_cobblestone", 22), Naturality::Unknown),
(("mossy_cobblestone", 8), Naturality::Built),
(("mycelium", 14), Naturality::Natural),
(("netherrack", 8), Naturality::Natural),
(("obsidian", 8), Naturality::Natural),
(("packed_ice", 140), Naturality::Natural),
(("packed_ice", 11), Naturality::Unknown),
(("quartz_ore", 8), Naturality::Exploited),
(("red_flower", 1), Naturality::Natural),
(("red_flower", 18), Naturality::Natural),
(("red_flower", 132), Naturality::Natural),
(("red_flower", 129), Naturality::Natural),
(("red_flower", 157), Naturality::Natural),
(("red_mushroom", 4), Naturality::Unknown),
(("red_mushroom", 6), Naturality::Natural),
(("red_mushroom", 14), Naturality::Natural),
(("red_mushroom_block", 14), Naturality::Natural),
(("red_mushroom_block", 29), Naturality::Natural),
(("red_mushroom_block", 157), Naturality::Natural),
(("red_sandstone", 2), Naturality::Exploited),
(("red_sandstone", 167), Naturality::Exploited),
(("red_sandstone", 39), Naturality::Exploited),
(("red_sandstone", 166), Naturality::Exploited),
(("red_sandstone", 38), Naturality::Exploited),
(("red_sandstone", 35), Naturality::Unknown),
(("reeds", 16), Naturality::Natural),
(("reeds", 6), Naturality::Natural),
(("reeds", 7), Naturality::Natural),
(("reeds", 21), Naturality::Natural),
(("sand", 0), Naturality::Natural),
(("sand", 16), Naturality::Natural),
(("sand", 2), Naturality::Natural),
(("sand", 7), Naturality::Natural),
(("sand", 6), Naturality::Natural),
(("sand", 130), Naturality::Natural),
(("sand", 24), Naturality::Natural),
(("sand", 3), Naturality::Pond),
(("sand", 4), Naturality::Pond),
(("sand", 1), Naturality::Pond),
(("sand", 167), Naturality::Pond),
(("sand", 166), Naturality::Pond),
(("sand", 38), Naturality::Pond),
(("sand", 39), Naturality::Pond),
(("sand", 18), Naturality::Pond),
(("sand", 5), Naturality::Pond),
(("sand", 132), Naturality::Pond),
(("sand", 13), Naturality::Exploited),
(("sand", 11), Naturality::Exploited),
(("sand", 8), Naturality::Built),
(("sandstone", 2), Naturality::Exploited),
(("sandstone", 130), Naturality::Exploited),
(("snow", 13), Naturality::Exploited),
(("snow", 140), Naturality::Exploited),
(("snow", 34), Naturality::Unknown),
(("snow", 20), Naturality::Unknown),
(("snow_layer", 13), Naturality::Natural),
(("snow_layer", 3), Naturality::Natural),
(("snow_layer", 20), Naturality::Natural),
(("snow_layer", 34), Naturality::Natural),
(("snow_layer", 158), Naturality::Natural),
(("snow_layer", 140), Naturality::Natural),
(("snow_layer", 133), Naturality::Natural),
(("snow_layer", 11), Naturality::Natural),
(("snow_layer", 5), Naturality::Unknown),
(("snow_layer", 12), Naturality::Unknown),
(("snow_layer", 30), Naturality::Unknown),
(("snow_layer", 162), Naturality::Unknown),
(("snow_layer", 26), Naturality::Unknown),
(("snow_layer", 131), Naturality::Unknown),
(("snow_layer", 32), Naturality::Unknown),
(("soul_sand", 8), Naturality::Natural),
(("soul_sand", 4), Naturality::Natural),
(("stained_hardened_clay", 167), Naturality::Natural),
(("stained_hardened_clay", 39), Naturality::Natural),
(("stained_hardened_clay", 166), Naturality::Natural),
(("stained_hardened_clay", 38), Naturality::Natural),
(("stone", 13), Naturality::Natural),
(("stone", 8), Naturality::Built),
(("tallgrass", 35), Naturality::Natural),
(("tallgrass", 1), Naturality::Natural),
(("tallgrass", 4), Naturality::Natural),
(("tallgrass", 129), Naturality::Natural),
(("tallgrass", 20), Naturality::Natural),
(("tallgrass", 166), Naturality::Natural),
(("tallgrass", 38), Naturality::Natural),
(("tallgrass", 163), Naturality::Natural),
(("tallgrass", 132), Naturality::Natural),
(("tallgrass", 0), Naturality::Built),
(("vine", 4), Naturality::Natural),
(("vine", 6), Naturality::Natural),
(("vine", 21), Naturality::Natural),
(("vine", 22), Naturality::Natural),
(("vine", 149), Naturality::Natural),
(("vine", 2), Naturality::Planted),
(("vine", 129), Naturality::Planted),
(("vine", 35), Naturality::Planted),
(("vine", 39), Naturality::Planted),
(("vine", 0), Naturality::Planted),
(("water", 130), Naturality::Built),
(("water", 24), Naturality::Natural),
(("water", 12), Naturality::Unknown),
(("water", 17), Naturality::Unknown),
(("water", 30), Naturality::Unknown),
(("water", 36), Naturality::Unknown),
(("water", 28), Naturality::Unknown),
(("water", 19), Naturality::Unknown),
(("water", 25), Naturality::Unknown),
(("water", 32), Naturality::Unknown),
(("water", 37), Naturality::Unknown),
(("water", 31), Naturality::Unknown),
(("water", 26), Naturality::Unknown),
(("water", 131), Naturality::Unknown),
(("water", 156), Naturality::Unknown),
(("water", 155), Naturality::Unknown),
(("water", 164), Naturality::Unknown),
(("water", 134), Naturality::Unknown),
(("water", 33), Naturality::Unknown),
(("water", 165), Naturality::Unknown),
(("water", 23), Naturality::Unknown),
(("water", 15), Naturality::Unknown),
(("water", 162), Naturality::Unknown),
(("waterlily", 6), Naturality::Natural),
(("waterlily", 0), Naturality::Unknown),
(("waterlily", 16), Naturality::Unknown),
(("waterlily", 7), Naturality::Unknown),
(("web", 4), Naturality::Natural),
(("yellow_flower", 1), Naturality::Natural),
(("yellow_flower", 129), Naturality::Natural),
(("yellow_flower", 3), Naturality::Unknown),
(("yellow_flower", 4), Naturality::Unknown),
(("yellow_flower", 18), Naturality::Unknown),
(("yellow_flower", 13), Naturality::Unknown),
(("yellow_flower", 5), Naturality::Unknown),
(("yellow_flower", 20), Naturality::Unknown),
(("yellow_flower", 29), Naturality::Unknown),
(("yellow_flower", 35), Naturality::Planted),
    ].iter().map(|((n,b),c)| ((*n, *b), *c)));
}
